name = "lustre_ssg_starter"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.3.5 and < 5.0.0"
lustre_ssg = ">= 0.8.0 and < 1.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
